"""update object table

Revision ID: 1df02402c8fb
Revises: ce73b88c9cec
Create Date: 2026-02-10 22:22:23.739194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df02402c8fb'
down_revision: Union[str, Sequence[str], None] = 'ce73b88c9cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('default_speed_for_devices', sa.Integer(), nullable=False))
    op.drop_column('object', 'default_speed_for_device')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('default_speed_for_device', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('object', 'default_speed_for_devices')
    # ### end Alembic commands ###
