"""update device table

Revision ID: 3f55679b935a
Revises: 89533d2ff914
Create Date: 2026-02-10 22:14:26.974404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f55679b935a'
down_revision: Union[str, Sequence[str], None] = '89533d2ff914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'default_speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('default_speed', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
