"""update object table

Revision ID: 600f375a121f
Revises: 948d9488cf26
Create Date: 2026-01-28 22:41:23.303018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600f375a121f'
down_revision: Union[str, Sequence[str], None] = '948d9488cf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'password_hash')
    # ### end Alembic commands ###
