"""add foreign key object_user

Revision ID: 846a823ea0d1
Revises: a7e2687ee343
Create Date: 2026-01-27 18:26:28.999839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846a823ea0d1'
down_revision: Union[str, Sequence[str], None] = 'a7e2687ee343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'object', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object', type_='foreignkey')
    op.drop_column('object', 'user_id')
    # ### end Alembic commands ###
