"""update device table

Revision ID: 89533d2ff914
Revises: fc5160c341db
Create Date: 2026-02-10 00:13:50.199395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89533d2ff914'
down_revision: Union[str, Sequence[str], None] = 'fc5160c341db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('default_speed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'default_speed')
    # ### end Alembic commands ###
