"""add foreign key device_object

Revision ID: 91cbb297c4e2
Revises: 846a823ea0d1
Create Date: 2026-01-27 18:27:04.937382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cbb297c4e2'
down_revision: Union[str, Sequence[str], None] = '846a823ea0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Device', sa.Column('object_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Device', 'object', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Device', type_='foreignkey')
    op.drop_column('Device', 'object_id')
    # ### end Alembic commands ###
