"""update object table

Revision ID: ce73b88c9cec
Revises: 3f55679b935a
Create Date: 2026-02-10 22:15:31.987427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce73b88c9cec'
down_revision: Union[str, Sequence[str], None] = '3f55679b935a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('default_speed_for_device', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'default_speed_for_device')
    # ### end Alembic commands ###
