"""update object table

Revision ID: fc5160c341db
Revises: 4a86b13c81c6
Create Date: 2026-02-06 19:45:52.925169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5160c341db'
down_revision: Union[str, Sequence[str], None] = '4a86b13c81c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('max_temperature', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'max_temperature')
    # ### end Alembic commands ###
